server:
  port: 9999
  servlet:
    context-path: /tm-user
    
spring:
  http: 
    encoding:
      charset: UTF-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_myBatis?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    
 #log4j
logging:
  config: classpath:log4j2-loc.xml
